<?php
    $categories = $this->getCategoryCollection();
    $categoryHelper = $this->getCategoryHelper();
    $_collectionSize = $categories->count();

?>
<div class="widget block block-static-block categorythumbnail" id="categorythumbnail">
    <div class="block-content">
        <div class="content-heading">
            <h2 class="title"><?php echo $this->getMainTitle(); ?></h2>
            <p class="info"><?php echo $this->getTagLine(); ?></p>
        </div>
        <div class="row items-<?php echo $_collectionSize ?>">
        <?php
        $i = 0;
        foreach($categories as $category): $i++;
            $cat = $this->getCategorymodel($category->getId());
            $image = $cat->getImageUrl(); ?>
            <div class=col-md-<?php echo $_collectionSize; ?> item-<?php echo $i; ?>">
            <?php if($image != null): ?>
                <a class="category_name category-image-container" href="<?php echo $cat->getUrl(); ?>">
                    <span class="category-image-container">
                        <span class="category-image-wrapper">
                            <img class="category-image-photo" src="<?php echo $image; ?>" class="img-responsive category_image" alt="<?php echo $cat->getName(); ?>" />
                        </span>
                    </span>
                    <h3 class="subcategory name image"><span><?php echo $cat->getName(); ?></span></h3>
                </a>
            <?php else: ?>
                <a class="category-item-link" href="<?php echo $cat->getUrl() ?>">
                    <h3 class="subcategory name no-image"<span><?php echo $cat->getName(); ?></span></h3>
                </a>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
        </div>
    </div>
</div>
